import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import {
  GetFriends,
  GetFriendsQuery,
  GetFriendsQueryVariables,
} from "../generated/graphql";
import { client } from "../utils/client";

interface Props {
  friends: GetFriendsQuery["friend"];
}

const Home: NextPage<Props> = ({ friends }) => {
  return (
    <div>
      <Head>
        <title>BYP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {friends.map((friend: any, i: number) => (
          <p key={friend.id}>{friend.username}</p>
        ))}
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  return client
    .query<GetFriendsQuery, GetFriendsQueryVariables>(GetFriends)
    .toPromise()
    .then((d) => {
      return { props: { friends: d.data?.friend } };
    })
    .catch((e) => {
      return { props: {} };
    });
};
